randomVariation/urls.py
from django.conf.urls import url 
from randomVariation.views import UserFormView
from . import views

app_name = 'randomVariation'

urlpatterns = [
	url(r'^$', views.Home, name='home'),
	url(r'^register/$', UserFormView.as_view(), name='register'),
	url(r'^secondLayer/$', views.secondLayer, name='secondLayer'),
	url(r'^rowSecondLayer/$', views.rowSecondLayer, name='rowSecondLayer'),	
	url(r'^thirdLayer/$', views.thirdLayer, name='thirdLayer'),	
]

rvSite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^', include('randomVariation.urls')),
	url(r'^admin/', admin.site.urls),
]

randomVariation/models.py
from django.db import models

# Create your models here.

randomVariation/forms.py
from django import forms 
from django.contrib.auth.models import User 

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ['username', 'email', 'password']

randomVariation/views.py
from django.shortcuts import render, get_object_or_404, redirect 
from django.contrib.auth.models import User
from django.contrib.auth import logout, login, authenticate
from django.views.generic import View
from .forms import UserForm


class UserFormView(View):
	form_class = UserForm
	template_name = 'registration/registration.html' #login.html
	#instance = get_object_or_404(User)

	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form':form})

	def post(self, request):
		form = self.form_class(request.POST)

		if form.is_valid():
			user = form.save(commit=False)
			#normalized data
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			#returns User object if credentials are correct
			user = authenticate(username=username, password=password)

			if user is not None:
				if user.is_active:
					login(request,user)
					return redirect('RFI:home')

		return render(request, self.template_name, {'form':form})

def Home(request):
	return render(request, 'randomVariation/home.html')

def secondLayer(request):
	return render(request, 'randomVariation/secondLayer.html')

def rowSecondLayer(request):
	return render(request, 'randomVariation/rowSecondLayer.html')

def thirdLayer(request):
	return render(request, 'randomVariation/thirdLayer.html')

randomVariation/templates/randomVariation/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>{% block title %}Random Variations{% endblock %}</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
	<link rel="stylesheet" type="text/css" href="../static/style.css">
	<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
	<div class="navbar navbar-inverse">
		<div class = "container-fluid">
			<!--Header-->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<!--<img src="../static/img/logo.png" class="nav navbar-nav right" style="padding:0px 5px 0px 5px;">-->
				<a href="{% url 'randomVariation:home' %}" class="navbar-brand">Random Variations</a>
			</div>
			<!--Items-->
			<div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="">
                        <a href="{% url 'randomVariation:home' %}">
                            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;
                            Home
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-baby-formula" aria-hidden="true"></span>&nbsp;
                            Random Variation form
                        </a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-left">
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-baby-formula" aria-hidden="true"></span>&nbsp;
                            Random Variation data
                        </a>
                    </li>
                </ul>
            </div>
		</div>
	</div>
	<div class="container-fluid">
		{% block content %}
		{% endblock %}
	</div>
</body>
</html>

randomVariation/templates/randomVariation/home.html
{% extends 'randomVariation/base.html'%}
{% block content %}
<script type="text/javascript" src="../static/dist/bundle.js"></script>

<div class = "row">
	<h3 class="textCenter">Hello User{{user.email}}!</h3>
</div>
<br>
<div class="textCenter">
	<button onclick="displayNotes()" type="button" class="btn btn-primary" id="firstChoice">Single Note</button>
	<br></br>
</div>
<div class="row textCenter" id="notesList" style="display: none">

		<input class="btn btn-warning" type="button" style="margin-top:10px" value="C"  onclick="getNote({type:'single note', value: {note:'C3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="C#" onclick="getNote({type:'single note', value: {note:'C#3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="D"  onclick="getNote({type:'single note', value: {note:'D3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="D#" onclick="getNote({type:'single note', value: {note:'D#3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="E"  onclick="getNote({type:'single note', value: {note:'E3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="F"  onclick="getNote({type:'single note', value: {note:'F3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="F#" onclick="getNote({type:'single note', value: {note:'F#3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="G"  onclick="getNote({type:'single note', value: {note:'G3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="G#" onclick="getNote({type:'single note', value: {note:'G#3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="A"  onclick="getNote({type:'single note', value: {note:'A3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="A#" onclick="getNote({type:'single note', value: {note:'A#3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="B"  onclick="getNote({type:'single note', value: {note:'B3'}})">

</div>
<br>
<div class="textCenter">
	<button onclick="displaySeq()" type="button" class="btn btn-info" id="firstChoice">Tone Row</button>
</div>
<br>
<div class="row textCenter" id="toneRow" style="display: none">

		<input class="btn btn-warning" type="button" style="margin-top:10px" value="C" onclick="getRow({type:'tone row', value: {note:'C3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="C#" onclick="getRow({type:'tone row', value: {note:'C#3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="D" onclick="getRow({type:'tone row', value: {note:'D3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="D#" onclick="getRow({type:'tone row', value: {note:'D#3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="E"  onclick="getRow({type:'tone row', value: {note:'E3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="F" onclick="getRow({type:'tone row', value: {note:'F3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="F#" onclick="getRow({type:'tone row', value: {note:'F#3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="G" onclick="getRow({type:'tone row', value: {note:'G3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="G#" onclick="getRow({type:'tone row', value: {note:'G#3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="A" onclick="getRow({type:'tone row', value: {note:'A3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="A#" onclick="getRow({type:'tone row', value: {note:'A#3'}})">
		<input class="btn btn-warning" type="button" style="margin-top:10px" value="B" onclick="getRow({type:'tone row', value: {note:'B3'}})">
</div>

<script type="text/javascript" src="../static/js/home.js"></script>

{% endblock %}

randomVariation/templates/randomVariation/rowSecondLayer.html
{% extends 'randomVariation/base.html' %}

{% block content %}
<div style="text-align:center">
	<script type="text/javascript" src="../static/dist/bundle.js"></script>
	<button type="button" class="btn btn-primary" id="btn1" onclick="displayScales()">Scales</button>
</div>
<br>
<div class="row textCenter" id="scalesList" style="display: none">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Major" onclick="getScale({type:'scale', value:{name:'Major'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Dorian"  onclick="getScale({type:'scale', value:{name:'Dorian'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Phrygian" onclick="getScale({type:'scale', value:{name:'Phrygian'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Lydian"  onclick="getScale({type:'scale', value:{name:'Lydian'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Mixolydian" onclick="getScale({type:'scale', value:{name: 'Mixolydian'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Aeloian" onclick="getScale({type:'scale', value:{name:'Aeloian'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Locrian"  onclick="getScale({type:'scale', value:{name:'Locian'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Augmented" onclick="getScale({type:'scale', value:{name:'Augmented'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Whole tone"  onclick="getScale({type:'scale', value:{name:'Whole Tone'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Harmonic minor" onclick="getScale({type:'scale', value:{name:'Harmonic minor'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Melodic minor ASC"  onclick="getScale({type:'scale', value:{name:'Melodic minor ASC'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Melodic minor DESC" onclick="getScale({type:'scale', value:{name:'Melodic minor DESC'}})">

</div>
<br>

<div class="row textCenter" style="display:none" id="scaleDirections">
	<input type="button" class="btn btn-warning" style="margin-top:10px" value="ASC" onclick="getDirection({type:'scale', value: {direction:'ASC'}})">
	<input type="button" class="btn btn-warning" style="margin-top:10px" value="DESC" onclick="getDirection({type:'scale', value: {direction:'DESC'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="ASC/DESC" onclick="getDirection({type:'scale', value:{directions:['ASC', 'DESC']}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="DESC/ASC" onclick="getDirection({type:'scale', value:{directions:['DESC', 'ASC']}})">
</div>
<br><br>

<div style="text-align:center">
	<button type="button" class="btn btn-primary" id="btn2" onclick="displayChords()">Chords</button>
</div>
<br>
<div class="row textCenter" id="chordsList" style="display: none">

	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Maj" onclick="getChord({type:'chord', value:{name: 'Maj'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Min" onclick="getChord({type:'chord', value:{name: 'Min'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Aug" onclick="getChord({type:'chord', value:{name: 'Aug'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Dim" onclick="getChord({type:'chord', value:{name: 'Dim'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Sus" onclick="getChord({type:'chord', value:{name: 'Sus'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Maj2" onclick="getChord({type:'chord', value:{name: 'Maj2'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Min2" onclick="getChord({type:'chord', value:{name: 'Min2'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Maj7" onclick="getChord({type:'chord', value:{name: 'Maj7'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="7"  onclick="getChord({type:'chord', value:{name: '7'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Min7" onclick="getChord({type:'chord', value:{name: 'Min7'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Half dim"  onclick="getChord({type:'chord', value:{name: 'Half dim'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Dim7" onclick="getChord({type:'chord', value:{name: 'Dim7'}})">
	<br>
</div>
<br>
<div class="row textCenter" style="display:none" id="chordDirections">
	<input type="button" class="btn btn-warning" style="margin-top:10px" value="ASC" onclick="getDirection({type:'chord', value: {direction:'ASC'}})">
	<input type="button" class="btn btn-warning" style="margin-top:10px" value="DESC" onclick="getDirection({type:'chord', value: {direction:'DESC'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="ASC/DESC" onclick="getDirection({type:'chord', value:{directions:['ASC', 'DESC']}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="DESC/ASC" onclick="getDirection({type:'chord', value:{directions:['DESC', 'ASC']}})">
</div>
<br><br>

<div style="text-align:center">
	<button type="button" class="btn btn-primary" id="btn2" onclick="create()">Generate</button>
</div>

<br>
<div class="row" style="text-align:center">
	<h2>Result</h2>
	<span id="output"></span>

</div>
<!--JavaScript-->

<script type="text/javascript" src="../static/js/rowSecondLayer.js"></script>

{% endblock%}

randomVariation/templates/randomVariation/secondLayer.html
{% extends 'randomVariation/base.html' %}
{% block content %}
<div style="text-align:center">
	<button type="button" class="btn btn-primary" id="btn1" onclick="displayScales()">Scales</button>

</div>
<br>

<div class="row textCenter" id="scalesList" style="display: none">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Major" onclick="getScale({type:'scale', value:{name:'Major'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Dorian"  onclick="getScale({type:'scale', value:{name:'Dorian'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Phrygian" onclick="getScale({type:'scale', value:{name:'Phrygian'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Lydian"  onclick="getScale({type:'scale', value:{name:'Lydian'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Mixolydian" onclick="getScale({type:'scale', value:{name: 'Mixolydian'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Aeolian" onclick="getScale({type:'scale', value:{name:'Aeloian'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Locrian"  onclick="getScale({type:'scale', value:{name:'Locrian'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Augmented" onclick="getScale({type:'scale', value:{name:'Augmented'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Whole tone"  onclick="getScale({type:'scale', value:{name:'Whole Tone'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Harmonic minor" onclick="getScale({type:'scale', value:{name:'Harmonic minor'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Melodic minor ASC"  onclick="getScale({type:'scale', value:{name:'Melodic minor ASC'}})">
	<input class="btn btn-warning" type="button"  style="margin-top:10px" value="Melodic minor DESC" onclick="getScale({type:'scale', value:{name:'Melodic minor DESC'}})">
</div>
<br>

<div class="row textCenter" style="display:none" id="scaleDirections">
	<input type="button" class="btn btn-warning" style="margin-top:10px" value="ASC" onclick="getDirection({type:'scale', value: {direction:'ASC'}})">
	<input type="button" class="btn btn-warning" style="margin-top:10px" value="DESC" onclick="getDirection({type:'scale', value: {direction:'DESC'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="ASC/DESC" onclick="getDirection({type:'scale', value:{directions:['ASC', 'DESC']}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="DESC/ASC" onclick="getDirection({type:'scale', value:{directions:['DESC', 'ASC']}})">
</div>
<br>

<div style="text-align:center">
	<button type="button" class="btn btn-primary" id="sequence" onClick="displaySeq()" >Sequence</button>
</div>
<br>
<div class="row textCenter" id="sequenceList" style="display: none">

	<input class="btn btn-warning" type="button" style="margin-top:10px" value="2m" onClick="getSeq({type:'sequence', value:{interval:1, direction:'ASC'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="2M" onClick="getSeq({type:'sequence', value:{interval:2, direction:'ASC'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="3m" onClick="getSeq({type:'sequence', value:{interval:3, direction:'ASC'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="3M" onClick="getSeq({type:'sequence', value:{interval:4, direction:'ASC'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="4" onClick="getSeq({type:'sequence', value:{interval:5, direction:'ASC'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="4x/5°" onClick="getSeq({type:'sequence', value:{interval:6, direction:'ASC'}})">

	<br>
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="ASC" onclick="getDirection({type:'sequence', value:{direction:'ASC'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="DESC" onclick="getDirection({type:'sequence', value:{direction:'DESC'}})">

</div>
<br><br>

<div style="text-align:center">
	<button type="button" class="btn btn-primary" id="btn3" onclick="displayChords()">Chords</button>
</div>
<br>
<div class="row textCenter" id="chordsList" style="display: none">

	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Maj" onclick="getChord({type:'chord', value:{name: 'Maj'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Min" onclick="getChord({type:'chord', value:{name: 'Min'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Aug" onclick="getChord({type:'chord', value:{name: 'Aug'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Dim" onclick="getChord({type:'chord', value:{name: 'Dim'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Sus" onclick="getChord({type:'chord', value:{name: 'Sus'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Maj2" onclick="getChord({type:'chord', value:{name: 'Maj2'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Min2" onclick="getChord({type:'chord', value:{name: 'Min2'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Maj7" onclick="getChord({type:'chord', value:{name: 'Maj7'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="7"  onclick="getChord({type:'chord', value:{name: '7'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Min7" onclick="getChord({type:'chord', value:{name: 'Min7'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Half dim"  onclick="getChord({type:'chord', value:{name: 'Half dim'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="Dim7" onclick="getChord({type:'chord', value:{name: 'Dim7'}})">
</div>
<br>

<div class="row textCenter" style="display:none" id="chordDirections">
	<input type="button" class="btn btn-warning" style="margin-top:10px" value="ASC" onclick="getDirection({type:'chord', value: {direction:'ASC'}})">
	<input type="button" class="btn btn-warning" style="margin-top:10px" value="DESC" onclick="getDirection({type:'chord', value: {direction:'DESC'}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="ASC/DESC" onclick="getDirection({type:'scale', value:{directions:['ASC', 'DESC']}})">
	<input class="btn btn-warning" type="button" style="margin-top:10px" value="DESC/ASC" onclick="getDirection({type:'scale', value:{directions:['DESC', 'ASC']}})">
</div>
<br>

<div class="row">
	<div style="text-align:center">
		<h4>Generate Now!</h4>
		<a href="#Scale">
			<button type="button" class="btn btn-primary" onclick="create()">Generate</button>
		</a>
	</div>
</div>
<br>
<div class="row" style="text-align:center">
	<h2>Result</h2>
	<span id="output"></span>
</div>

<!--JavaScript-->
<script type="text/javascript" src="../static/dist/bundle.js"></script>
<script type="text/javascript" src="../static/js/secondLayer.js"></script>
{% endblock %}